// Auto-generated by scripts/generate-models.ts
// Do not edit manually.
// Generated: 2026-06-01T06:02:36.310Z
// Model count: 37

import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";

export const GENERATED_MODELS: ProviderModelConfig[] = 
[
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 163840,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "cogito-2.1:671b",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "cogito-2.1:671b",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 163840,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "deepseek-v3.1:671b",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "deepseek-v3.1:671b",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 163840,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "deepseek-v3.2",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "deepseek-v3.2",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 1048576,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "deepseek-v4-flash",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "deepseek-v4-flash",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 1048576,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "deepseek-v4-pro",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "deepseek-v4-pro",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "devstral-2:123b",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "devstral-2:123b",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "devstral-small-2:24b",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "devstral-small-2:24b",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 1048576,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "gemini-3-flash-preview",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "gemini-3-flash-preview",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "gemma4:31b",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "gemma4:31b",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 202752,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "glm-4.6",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "glm-4.6",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 202752,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "glm-4.7",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "glm-4.7",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 202752,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "glm-5",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "glm-5",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 202752,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "glm-5.1",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "glm-5.1",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 131072,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "gpt-oss:120b",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "gpt-oss:120b",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": null,
      "xhigh": null
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 131072,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "gpt-oss:20b",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "gpt-oss:20b",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": null,
      "xhigh": null
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "kimi-k2-thinking",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "kimi-k2-thinking",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": null,
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "kimi-k2:1t",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "kimi-k2:1t",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "kimi-k2.5",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "kimi-k2.5",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "kimi-k2.6",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "kimi-k2.6",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 204800,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "minimax-m2",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "minimax-m2",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 204800,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "minimax-m2.1",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "minimax-m2.1",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": null,
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 196608,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "minimax-m2.5",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "minimax-m2.5",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": null,
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 196608,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "minimax-m2.7",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "minimax-m2.7",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": null,
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 524288,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "minimax-m3",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "minimax-m3",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": null,
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "ministral-3:14b",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "ministral-3:14b",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "ministral-3:3b",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "ministral-3:3b",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "ministral-3:8b",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "ministral-3:8b",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "mistral-large-3:675b",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "mistral-large-3:675b",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "nemotron-3-nano:30b",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "nemotron-3-nano:30b",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "nemotron-3-super",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "nemotron-3-super",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "qwen3-coder-next",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "qwen3-coder-next",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "qwen3-coder:480b",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "qwen3-coder:480b",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "qwen3-next:80b",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "qwen3-next:80b",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": null,
      "low": null,
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": null
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "qwen3-vl:235b",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "qwen3-vl:235b",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": "high",
      "low": "low",
      "medium": "medium",
      "minimal": null,
      "off": null,
      "xhigh": "max"
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "qwen3-vl:235b-instruct",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "qwen3-vl:235b-instruct",
    "reasoning": false
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 262144,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "qwen3.5:397b",
    "input": [
      "text",
      "image"
    ],
    "maxTokens": 32768,
    "name": "qwen3.5:397b",
    "reasoning": true,
    "thinkingLevelMap": {
      "high": null,
      "low": null,
      "medium": "medium",
      "minimal": null,
      "off": "none",
      "xhigh": null
    }
  },
  {
    "compat": {
      "maxTokensField": "max_tokens",
      "openRouterRouting": {},
      "requiresAssistantAfterToolResult": false,
      "requiresReasoningContentOnAssistantMessages": false,
      "requiresThinkingAsText": false,
      "requiresToolResultName": false,
      "sendSessionAffinityHeaders": false,
      "supportsDeveloperRole": false,
      "supportsLongCacheRetention": false,
      "supportsReasoningEffort": true,
      "supportsStore": false,
      "supportsStrictMode": false,
      "supportsUsageInStreaming": true,
      "thinkingFormat": "openai",
      "vercelGatewayRouting": {},
      "zaiToolStream": false
    },
    "contextWindow": 32768,
    "cost": {
      "cacheRead": 0,
      "cacheWrite": 0,
      "input": 0,
      "output": 0
    },
    "id": "rnj-1:8b",
    "input": [
      "text"
    ],
    "maxTokens": 32768,
    "name": "rnj-1:8b",
    "reasoning": false
  }
];
