// Auto-generated by scripts/generate-reasoning.ts
// Do not edit manually.
// Model count: 24

export type ModelsDevReasoningOption =
  | { type: "toggle" }
  | {
      type: "effort";
      values: Array<"none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max" | "ultra" | "default" | null>;
    };

export const MODEL_REASONING_OPTIONS: Record<string, ModelsDevReasoningOption[]> = {
  "deepseek-v4-flash": [{ type: "toggle" }, { type: "effort", values: ["high", "max"] }],
  "deepseek-v4-flash:0731": [{ type: "toggle" }, { type: "effort", values: ["high", "max"] }],
  "deepseek-v4-pro": [{ type: "toggle" }, { type: "effort", values: ["high", "max"] }],
  "deepseek-v4-pro:0813": [{ type: "toggle" }, { type: "effort", values: ["high", "max"] }],
  "deepseek-v4.1-flash": [{ type: "toggle" }, { type: "effort", values: ["low", "high", "max"] }],
  "gemma4:31b": [{ type: "toggle" }],
  "glm-5.1": [{ type: "toggle" }],
  "glm-5.2": [{ type: "effort", values: ["high", "max"] }],
  "glm-5.3": [{ type: "effort", values: ["low", "high", "max"] }],
  "glm-5.3-flash": [{ type: "effort", values: ["low", "high", "max"] }],
  "gpt-oss:120b": [{ type: "effort", values: ["low", "medium", "high"] }],
  "gpt-oss:20b": [{ type: "effort", values: ["low", "medium", "high"] }],
  "kimi-k2.5": [{ type: "toggle" }],
  "kimi-k2.6": [{ type: "toggle" }],
  "kimi-k2.7-code": [{ type: "toggle" }],
  "kimi-k3": [{ type: "toggle" }, { type: "effort", values: ["low", "high", "max"] }],
  "minimax-m2.5": [],
  "minimax-m2.7": [{ type: "toggle" }],
  "minimax-m3": [{ type: "toggle" }, { type: "effort", values: ["low", "medium", "high", "max"] }],
  "mistral-large-4": [{ type: "effort", values: ["none", "high"] }],
  "nemotron-3-nano:30b": [{ type: "toggle" }],
  "nemotron-3-super": [{ type: "toggle" }],
  "nemotron-3-ultra": [{ type: "toggle" }],
  "qwen3.5:397b": [{ type: "toggle" }],
};
