#!/usr/bin/env tsx
/**
 * Fetches models from the Ollama Cloud API and writes them to
 * models.generated.ts. Run manually and commit the output when
 * the model catalog changes.
 *
 * Usage:
 *   npm install  # ensure tsx is available
 *   npm run generate-models
 */

import { writeFileSync } from "node:fs";
import { assembleModels, fetchModelIds, refreshOllamaCloudModels } from "../models.ts";

// Models announced for retirement used to be excluded from the generated list
// via RETIRED_MODEL_IDS. GENERATED_MODELS is now only a first-launch fallback
// and the live refresh surfaces whatever the API returns, so there's no need to
// curate retired models out of the baked-in list.
const RETIRED_MODEL_IDS = new Set<string>([]);

console.log("Fetching Ollama Cloud models...");
const modelIds = await fetchModelIds();
const { models: raw, failed } = await refreshOllamaCloudModels(modelIds);
if (failed > 0) {
  console.warn(
    `  ${failed} model detail fetch(es) failed; generating from the ${Object.keys(raw).length} that succeeded.`,
  );
}

const assembled = assembleModels(raw);
const models = assembled.filter((m) => !RETIRED_MODEL_IDS.has(m.id));
const retired = assembled.length - models.length;
console.log(
  `\nAssembled ${assembled.length} tool-capable models (${retired} retired, ${models.length} shipped).`,
);

// Stable serialization: sort models by id and object keys so field order
// changes in the source don't produce gratuitous diffs. `id` and `name`
// come first to make it easy to spot a model in the generated file.
const PREFERRED_KEYS = ["id", "name"];
function sortKeys(obj: unknown): unknown {
  if (obj && typeof obj === "object" && !Array.isArray(obj)) {
    return Object.keys(obj)
      .sort((a, b) => {
        const ai = PREFERRED_KEYS.indexOf(a);
        const bi = PREFERRED_KEYS.indexOf(b);
        if (ai !== -1 && bi !== -1) return ai - bi;
        if (ai !== -1) return -1;
        if (bi !== -1) return 1;
        return a < b ? -1 : a > b ? 1 : 0;
      })
      .reduce(
        (sorted, k) => {
          sorted[k] = sortKeys((obj as Record<string, unknown>)[k]);
          return sorted;
        },
        {} as Record<string, unknown>,
      );
  }
  if (Array.isArray(obj)) return obj.map(sortKeys);
  return obj;
}

const sortedModels = [...models].sort((a, b) => {
  const aid = a.id ?? "";
  const bid = b.id ?? "";
  return aid < bid ? -1 : aid > bid ? 1 : 0;
});

const out = [
  "// Auto-generated by scripts/generate-models.ts",
  "// Do not edit manually.",
  `// Generated: ${new Date().toISOString()}`,
  `// Model count: ${models.length}`,
  "",
  'import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";',
  "",
  "export const GENERATED_MODELS: ProviderModelConfig[] = ",
  `${JSON.stringify(sortKeys(sortedModels), null, 2)};`,
  "",
].join("\n");

writeFileSync("models.generated.ts", out);
console.log(`Wrote models.generated.ts (${models.length} models).`);
