#!/usr/bin/env tsx
/**
 * Probes per-model max output tokens from the live API and writes
 * limits.generated.ts. Run manually (or via CI) and commit the output.
 *
 * Usage:
 *   OLLAMA_API_KEY=<key> npm run generate-limits
 *
 * The /api/show endpoint does not expose an output limit
 * (https://docs.ollama.com/api-reference/show-model-details,
 * https://github.com/ollama/ollama/issues/7222), so each model is probed with
 * a minimal chat completion: an ascending max_tokens tier plus a stop
 * sequence. A rejected request reports the exact limit in the error message:
 *   max_tokens (100000) exceeds model's maximum output tokens (65536) for model ...
 *
 * Models whose limit could not be determined are omitted from the generated
 * table and fall back to 32768 at runtime (see resolveMaxTokens in models.ts).
 */

import { writeFileSync } from "node:fs";
import { fetchModelIds, OLLAMA_BASE } from "../models.ts";
import { concurrentMap, fetchJsonWithTimeout } from "../utils.ts";

const PROBE_TIERS = [65536, 131072, 262144, 524288];
// Generous timeout: some models (e.g. nemotron-3-ultra) take >15s to first
// token, and a timeout drops the model from the table (32768 fallback at
// runtime), which is worse than a slow probe.
const PROBE_TIMEOUT_MS = 60000;
const LIMIT_RE = /maximum output tokens \((\d+)\)/;

/** Probe one model; returns the exact limit, or undefined when unknown. */
async function probeMaxTokens(id: string): Promise<number | undefined> {
  const limit = PROBE_TIERS[PROBE_TIERS.length - 1];
  for (const tier of PROBE_TIERS) {
    const res = await fetchJsonWithTimeout<{ error?: { message?: string } }>(
      `${OLLAMA_BASE}/v1/chat/completions`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.OLLAMA_API_KEY}`,
        },
        body: JSON.stringify({
          model: id,
          messages: [{ role: "user", content: "Reply with exactly: OK" }],
          max_tokens: tier,
          stop: ["OK"],
        }),
      },
      PROBE_TIMEOUT_MS,
    );
    if (res.ok) {
      // Limit is at least this tier; keep ascending.
      continue;
    }
    const match = LIMIT_RE.exec(res.error ?? "");
    if (match) {
      return Number(match[1]);
    }
    // Rejected for a reason we cannot parse (e.g. billing, rate limit).
    return undefined;
  }
  return limit;
}

if (!process.env.OLLAMA_API_KEY) {
  console.error("OLLAMA_API_KEY is required (chat completions are authenticated).");
  process.exit(1);
}

console.log("Fetching Ollama Cloud models...");
const modelIds = await fetchModelIds();
console.log(`Probing ${modelIds.length} models for max output tokens...`);

const results = await concurrentMap(modelIds, 8, async (id) => ({ id, limit: await probeMaxTokens(id) }));

const limits: Record<string, number> = {};
let failed = 0;
for (const result of results) {
  if (result.status === "fulfilled" && result.value.limit !== undefined) {
    limits[result.value.id] = result.value.limit;
  } else {
    failed++;
    const id = result.status === "fulfilled" ? result.value.id : "unknown";
    console.warn(`  no limit for ${id}; runtime will fall back to 32768`);
  }
}

const out = [
  "// Auto-generated by scripts/generate-limits.ts",
  "// Do not edit manually.",
  `// Probed models: ${Object.keys(limits).length} (${failed} failed)`,
  "",
  "export const MODEL_MAX_OUTPUT_TOKENS: Record<string, number> = {",
  ...Object.keys(limits)
    .sort()
    .map((id) => `  "${id}": ${limits[id]},`),
  "};",
  "",
].join("\n");

writeFileSync("limits.generated.ts", out);
console.log(`Wrote limits.generated.ts (${Object.keys(limits).length} models, ${failed} failed).`);
